#!/usr/bin/env node

/**
 * generate-tokens.js — Single-source token generation pipeline.
 *
 * Parses the YAML front-matter from DESIGN.md and emits consumable artifacts:
 *   dist/tailwind.config.js  — Tailwind theme mapping (semantic token classes)
 *   dist/tokens.css          — CSS custom properties (--vi-*)
 *   dist/tokens.json         — Machine-readable JSON for MCP and tooling
 *
 * Usage:
 *   node scripts/generate-tokens.js          # write to dist/
 *   node scripts/generate-tokens.js --dry-run # print to stdout
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DESIGN_FILE = path.join(ROOT, 'DESIGN.md');
const DIST_DIR = path.join(ROOT, 'dist');

// --- Minimal YAML parser (handles the flat key: "value" format in DESIGN.md) ---

function parseFrontMatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) throw new Error('No YAML front-matter found in DESIGN.md');
  const yaml = match[1];

  const tokens = {};
  let currentCategory = null;

  for (const line of yaml.split('\n')) {
    if (line.startsWith('#') || line.trim() === '') continue;

    // Category line: two spaces of indent, word: at start
    const catMatch = line.match(/^(\w+):$/);
    if (catMatch && !line.startsWith(' ')) {
      currentCategory = catMatch[1];
      tokens[currentCategory] = {};
      continue;
    }

    // Token line: indented key: "value"
    const tokenMatch = line.match(/^\s+(\S+):\s+"?([^"\n]+)"?$/);
    if (tokenMatch && currentCategory) {
      const [, key, value] = tokenMatch;
      tokens[currentCategory][key] = value;
    }
  }

  return tokens;
}

// --- Emitters ---

function emitTailwindConfig(tokens) {
  const theme = {};

  for (const [category, entries] of Object.entries(tokens)) {
    for (const [key, value] of Object.entries(entries)) {
      // Each token key is already in the format: role-variant-state
      // Use the full key as the Tailwind theme name.
      if (!theme[category]) theme[category] = {};
      theme[category][key] = value;
    }
  }

  // Build the config object with special Tailwind mappings
  const config = {
    content: ['./preview/**/*.html', './src/**/*.{js,jsx,ts,tsx,html}'],
    theme: {
      extend: {
        colors: theme.colors || {},
        fontFamily: {
          'typography-family-sans-base': ['Inter', 'sans-serif'],
          'typography-family-mono-base': ['JetBrains Mono', 'monospace'],
        },
        fontSize: theme.typography && Object.fromEntries(
          Object.entries(theme.typography)
            .filter(([k]) => k.startsWith('typography-size-'))
            .map(([k, v]) => [k, v])
        ),
        backdropBlur: {
          sm: '4px',
          md: '8px',
          lg: '16px',
        },
        borderRadius: theme.spacing
          ? Object.fromEntries(
              Object.entries(theme.spacing)
                .filter(([k]) => k.startsWith('layout-radius-'))
                .map(([k, v]) => [k, v])
            )
          : {},
        padding: {
          ...theme.spacing,
          ...theme.space,
        },
        gap: theme.space || {},
        width: theme.size || {},
        height: theme.size || {},
        transitionDuration: theme.transition || {},
      },
    },
    plugins: [],
  };

  return `/** GENERATED BY scripts/generate-tokens.js — DO NOT EDIT. */
/** Source: DESIGN.md YAML front-matter. Run \`npm run tokens\` to regenerate. */

module.exports = ${JSON.stringify(config, null, 2)};
`;
}

function emitCSS(tokens) {
  const lines = [
    '/* GENERATED BY scripts/generate-tokens.js — DO NOT EDIT. */',
    '/* Source: DESIGN.md YAML front-matter. Run `npm run tokens` to regenerate. */',
    ':root {',
  ];

  for (const [category, entries] of Object.entries(tokens)) {
    for (const [key, value] of Object.entries(entries)) {
      const cssVar = `--vi-${category}-${key}`;
      lines.push(`  ${cssVar}: ${value};`);
    }
  }

  lines.push('}');
  return lines.join('\n') + '\n';
}

function emitJSON(tokens) {
  return JSON.stringify(tokens, null, 2) + '\n';
}

// --- Main ---

function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');

  const content = fs.readFileSync(DESIGN_FILE, 'utf-8');
  const tokens = parseFrontMatter(content);

  const outputs = {
    'tailwind.config.js': emitTailwindConfig(tokens),
    'tokens.css': emitCSS(tokens),
    'tokens.json': emitJSON(tokens),
  };

  if (dryRun) {
    for (const [file, content] of Object.entries(outputs)) {
      process.stdout.write(`\n=== dist/${file} ===\n`);
      process.stdout.write(content);
    }
    return;
  }

  if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
  }

  for (const [file, content] of Object.entries(outputs)) {
    const filePath = path.join(DIST_DIR, file);
    fs.writeFileSync(filePath, content, 'utf-8');
    process.stdout.write(`wrote dist/${file}\n`);
  }
}

if (require.main === module) {
  main();
}

module.exports = { parseFrontMatter, emitTailwindConfig, emitCSS, emitJSON };
